// Türkiye 81 ili — merkez koordinatları (enlem/boylam)
// Haritada daire olarak gösterilecek

export const CITIES: {
  id: string;
  name: string;
  lat: number;
  lng: number;
  region: string;
}[] = [
  // İç Anadolu
  { id: "ankara", name: "Ankara", lat: 39.93, lng: 32.86, region: "İç Anadolu" },
  { id: "konya", name: "Konya", lat: 37.87, lng: 32.49, region: "İç Anadolu" },
  { id: "kayseri", name: "Kayseri", lat: 38.73, lng: 35.49, region: "İç Anadolu" },
  { id: "eskisehir", name: "Eskişehir", lat: 39.78, lng: 30.52, region: "İç Anadolu" },
  { id: "sivas", name: "Sivas", lat: 39.75, lng: 37.02, region: "İç Anadolu" },
  { id: "aksaray", name: "Aksaray", lat: 38.37, lng: 34.04, region: "İç Anadolu" },
  { id: "nevsehir", name: "Nevşehir", lat: 38.62, lng: 34.71, region: "İç Anadolu" },
  { id: "nigde", name: "Niğde", lat: 37.97, lng: 34.68, region: "İç Anadolu" },
  { id: "kirikkale", name: "Kırıkkale", lat: 39.84, lng: 33.51, region: "İç Anadolu" },
  { id: "kirsehir", name: "Kırşehir", lat: 39.15, lng: 34.16, region: "İç Anadolu" },
  { id: "yozgat", name: "Yozgat", lat: 39.82, lng: 34.81, region: "İç Anadolu" },
  { id: "cankiri", name: "Çankırı", lat: 40.60, lng: 33.62, region: "İç Anadolu" },
  // Marmara
  { id: "istanbul", name: "İstanbul", lat: 41.01, lng: 28.97, region: "Marmara" },
  { id: "bursa", name: "Bursa", lat: 40.18, lng: 29.07, region: "Marmara" },
  { id: "tekirdag", name: "Tekirdağ", lat: 40.98, lng: 27.51, region: "Marmara" },
  { id: "edirne", name: "Edirne", lat: 41.68, lng: 26.56, region: "Marmara" },
  { id: "kirklareli", name: "Kırklareli", lat: 41.73, lng: 27.22, region: "Marmara" },
  { id: "canakkale", name: "Çanakkale", lat: 40.15, lng: 26.41, region: "Marmara" },
  { id: "balikesir", name: "Balıkesir", lat: 39.65, lng: 27.89, region: "Marmara" },
  { id: "kocaeli", name: "Kocaeli", lat: 40.85, lng: 29.88, region: "Marmara" },
  { id: "sakarya", name: "Sakarya", lat: 40.69, lng: 30.43, region: "Marmara" },
  { id: "bolu", name: "Bolu", lat: 40.74, lng: 31.61, region: "Marmara" },
  { id: "bilecik", name: "Bilecik", lat: 40.15, lng: 29.98, region: "Marmara" },
  { id: "yalova", name: "Yalova", lat: 40.65, lng: 29.28, region: "Marmara" },
  // Ege
  { id: "izmir", name: "İzmir", lat: 38.42, lng: 27.14, region: "Ege" },
  { id: "manisa", name: "Manisa", lat: 38.61, lng: 27.43, region: "Ege" },
  { id: "aydin", name: "Aydın", lat: 37.85, lng: 27.84, region: "Ege" },
  { id: "mugla", name: "Muğla", lat: 37.22, lng: 28.36, region: "Ege" },
  { id: "denizli", name: "Denizli", lat: 37.77, lng: 29.09, region: "Ege" },
  { id: "usak", name: "Uşak", lat: 38.68, lng: 29.41, region: "Ege" },
  { id: "kutahya", name: "Kütahya", lat: 39.42, lng: 29.98, region: "Ege" },
  { id: "afyonkarahisar", name: "Afyonkarahisar", lat: 38.76, lng: 30.54, region: "Ege" },
  // Akdeniz
  { id: "antalya", name: "Antalya", lat: 36.90, lng: 30.71, region: "Akdeniz" },
  { id: "mersin", name: "Mersin", lat: 36.80, lng: 34.63, region: "Akdeniz" },
  { id: "adana", name: "Adana", lat: 37.00, lng: 35.32, region: "Akdeniz" },
  { id: "hatay", name: "Hatay", lat: 36.40, lng: 36.35, region: "Akdeniz" },
  { id: "kahramanmaras", name: "Kahramanmaraş", lat: 37.59, lng: 36.94, region: "Akdeniz" },
  { id: "osmaniye", name: "Osmaniye", lat: 37.07, lng: 36.25, region: "Akdeniz" },
  { id: "burdur", name: "Burdur", lat: 37.72, lng: 30.29, region: "Akdeniz" },
  { id: "isparta", name: "Isparta", lat: 37.76, lng: 30.56, region: "Akdeniz" },
  // Karadeniz
  { id: "samsun", name: "Samsun", lat: 41.29, lng: 36.33, region: "Karadeniz" },
  { id: "trabzon", name: "Trabzon", lat: 41.00, lng: 39.73, region: "Karadeniz" },
  { id: "ordu", name: "Ordu", lat: 40.98, lng: 37.88, region: "Karadeniz" },
  { id: "giresun", name: "Giresun", lat: 40.91, lng: 38.39, region: "Karadeniz" },
  { id: "rize", name: "Rize", lat: 41.02, lng: 40.52, region: "Karadeniz" },
  { id: "artvin", name: "Artvin", lat: 41.18, lng: 41.82, region: "Karadeniz" },
  { id: "kastamonu", name: "Kastamonu", lat: 41.37, lng: 33.78, region: "Karadeniz" },
  { id: "sinop", name: "Sinop", lat: 42.02, lng: 35.15, region: "Karadeniz" },
  { id: "bartin", name: "Bartın", lat: 41.63, lng: 32.34, region: "Karadeniz" },
  { id: "zonguldak", name: "Zonguldak", lat: 41.46, lng: 31.80, region: "Karadeniz" },
  { id: "karabuk", name: "Karabük", lat: 41.20, lng: 32.63, region: "Karadeniz" },
  { id: "duzce", name: "Düzce", lat: 40.84, lng: 31.16, region: "Karadeniz" },
  { id: "amasya", name: "Amasya", lat: 40.65, lng: 35.83, region: "Karadeniz" },
  { id: "tokat", name: "Tokat", lat: 40.31, lng: 36.56, region: "Karadeniz" },
  { id: "corum", name: "Çorum", lat: 40.55, lng: 34.95, region: "Karadeniz" },
  // Doğu Anadolu
  { id: "erzurum", name: "Erzurum", lat: 39.91, lng: 41.27, region: "Doğu Anadolu" },
  { id: "van", name: "Van", lat: 38.50, lng: 43.38, region: "Doğu Anadolu" },
  { id: "malatya", name: "Malatya", lat: 38.35, lng: 38.31, region: "Doğu Anadolu" },
  { id: "elazig", name: "Elazığ", lat: 38.67, lng: 39.22, region: "Doğu Anadolu" },
  { id: "erzincan", name: "Erzincan", lat: 39.75, lng: 39.49, region: "Doğu Anadolu" },
  { id: "agri", name: "Ağrı", lat: 39.72, lng: 43.05, region: "Doğu Anadolu" },
  { id: "kars", name: "Kars", lat: 40.60, lng: 43.10, region: "Doğu Anadolu" },
  { id: "igdir", name: "Iğdır", lat: 39.92, lng: 44.05, region: "Doğu Anadolu" },
  { id: "ardahan", name: "Ardahan", lat: 41.11, lng: 42.70, region: "Doğu Anadolu" },
  { id: "tunceli", name: "Tunceli", lat: 39.11, lng: 39.55, region: "Doğu Anadolu" },
  { id: "bingol", name: "Bingöl", lat: 38.88, lng: 40.50, region: "Doğu Anadolu" },
  { id: "mus", name: "Muş", lat: 38.74, lng: 41.49, region: "Doğu Anadolu" },
  { id: "bitlis", name: "Bitlis", lat: 38.40, lng: 42.12, region: "Doğu Anadolu" },
  { id: "hakkari", name: "Hakkari", lat: 37.57, lng: 43.74, region: "Doğu Anadolu" },
  // Güneydoğu Anadolu
  { id: "gaziantep", name: "Gaziantep", lat: 37.06, lng: 37.38, region: "Güneydoğu Anadolu" },
  { id: "diyarbakir", name: "Diyarbakır", lat: 37.91, lng: 40.22, region: "Güneydoğu Anadolu" },
  { id: "sanliurfa", name: "Şanlıurfa", lat: 37.16, lng: 38.80, region: "Güneydoğu Anadolu" },
  { id: "mardin", name: "Mardin", lat: 37.31, lng: 40.74, region: "Güneydoğu Anadolu" },
  { id: "batman", name: "Batman", lat: 37.89, lng: 41.13, region: "Güneydoğu Anadolu" },
  { id: "siirt", name: "Siirt", lat: 37.93, lng: 41.95, region: "Güneydoğu Anadolu" },
  { id: "sirnak", name: "Şırnak", lat: 37.52, lng: 42.46, region: "Güneydoğu Anadolu" },
  { id: "kilis", name: "Kilis", lat: 36.72, lng: 37.12, region: "Güneydoğu Anadolu" },
  { id: "adiyaman", name: "Adıyaman", lat: 37.76, lng: 38.28, region: "Güneydoğu Anadolu" },
];
